services:
  app:
    build:
      context: .

    ports:
      - '8000:8000'

    volumes:
      - ./drf_test_task_app:/drf_test_task_app

    environment:
      - 'DB_HOST=database'
      - 'DB_NAME=${DB_NAME}'
      - 'DB_USER=${DB_USER}'
      - 'DB_PASSWORD=${DB_PASSWORD}'

    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - database

  database:
    image: postgres:16-alpine

    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
